version: '2'

services:

  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ".:/api"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: password